package main

var (
	badIngredientsMap = map[string]bool{
		"carrageenan": true, "sugar": true, "fluoride": true, "aluminum": true,
		"sodium aluminum phosphate": true, "sodium aluminum sulfate": true,
		"arsenic": true, "rice syrup": true, "cadmium": true, "lead": true,
		"mercury": true, "monosodium glutamate": true, "msg": true, "alachlor": true,
		"acetochlor": true, "metolachlor": true, "atrazine": true,
		"simazine": true, "cyanazine": true, "processed free glutamic acid": true,
		"organophosphates": true, "malathion": true, "diazinon": true,
		"dichlorvos": true, "fenthion": true, "chlorpyrif": true,
		"glyphosate": true, "polyethoxylated tallowamine": true, "poea": true,
		"phosphates": true, "bpa": true, "bisphenol a": true, "1-bromopropane": true, "1-bp": true, "1 bromopropane": true,
		"di(2-ethylhexyl)adipate": true, "bis(2-ethylhexyl)adipate": true, "dioctyladipate": true, "deha": true, "dioxins": true, "dioctyl adipate": true,
		"hexanedioic acid": true, "ethylbenzene": true, "glycol ethers": true, "methylene chloride": true,
		"p-dichlorobenzene": true, "phthalates": true, "styrene": true,
		"white refined flour": true, "white refined sugar": true,
		"artificial color": true, "yellow 5": true, "4-methylimidazole": true, "4 methylimidazole": true,
		"4-mei": true, "butylated hydroxyanisole": true, "bht": true, "butylated hydroxytoluene": true,
		"nitrites": true, "propionates": true, "parabens": true, "methylparaben": true,
		"ethylparaben": true, "propylparaben": true, "potassium sorbate": true,
		"sodium benzoate": true, "potassium benzoate": true, "calcium benzoate": true,
		"benzene": true, "artificial sweetener": true, "aspartame": true,
		"sucralose": true, "saccharin": true, "recombinant bovine growth hormone": true, "rbgh": true,
		"high fructose corn syrup": true, "hfcs": true, "maize syrup": true, "glucose syrup": true,
		"tapioca syrup": true, "fruit fructose": true, "crystalline fructose": true,
		"fructose": true, "hydrogenated oil": true, "pfcs": true, "perfluorinated compounds": true,
		"perfluorooctanoic acid": true, "pfoa": true, "pfos": true, "perfluorooctane sulfonic acid": true,
		"ptfe": true, "polytetrafluoroetheylene": true, "artificial flavors": true,
		"hydrolyzed vegetable protein": true, "natural flavors": true,
		"tvp": true, "textured vegetable protein": true, "perfluorinated chemicals": true, "perfluorochemicals": true, "pfc": true,
		"fluorotelomer": true, "teflon": true, "c8": true, "c7": true, "c9": true,
		"c10": true, "c11": true, "c12": true, "dioxin": true,
		"2 tetrachlorodibenzo para dioxin": true, "tcdd": true, "3 tetrachlorodibenzo para dioxin": true,
		"7 tetrachlorodibenzo para dioxin": true, "8 tetrachlorodibenzo para dioxin": true,
		"polychlorinated dibenzo para dioxins": true, "pcdds": true, "polychlorinated dibenzofurans": true, "pcdfs": true,
		"polychlorinated biphenyls": true, "pcbs": true, "canola oil": true, "sunflower oil": true, "safflower oil": true,
		"vegetable oil": true, "palm oil": true, "partially hydrogenated oil": true, "corn oil": true, "rapeseed oil": true, "soy oil": true,
		"rice bran oil": true, "grapeseed oil": true, "red 40": true, "yellow 6": true, "blue 1": true, "blue 2 ": true, "green 3": true, "red 3": true,
		"citrus red": true, "artifical color": true, "natural smoke flavor": true, "soy bean oil": true, "corn syrup": true, "cottonseed oil": true,
		"malted cereal syrup": true, "sodium nitrite": true, "potassium nitrate": true, "celery powder": true, "celery juice": true, "cured": true,
		"curing": true, "nitrate": true, "nitrite": true, "niacin": true, "nicotinic acid": true, "potassium bromate": true,
		"heterocyclic amines": true, "polycyclic aromatic hydrocarbons": true, "titanium dioxide": true, "artificial": true, "tbhq": true,
		"tert butylhydroquinone": true, "azodicarbonamide": true, "ada": true,
		"brominated vegetable oil": true, "bvo": true, "propyl parabens": true, "propyl gallate": true, "caramel color": true, "edta": true, "calcium disodium": true, "emulsifier lecithine": true, "Soy Lecithin": true, "emulsifier lecithin": true,
		"flavour enhancers": true, "inosinato": true, "guanylate disódicos": true, "smoke flavouring": true, "colouring": true,
		"skimmed milk powder": true, "sunflower lecithin": true, "soybean oil": true,
		"e101a": true, "riboflavin 5 phosphate": true, "e338": true, "phosphoric acid": true, "e339": true, "sodium phosphate": true,
		"e340": true, "potassium phosphate": true, "e341": true, "calcium phosphate": true, "e343": true, "magnesium phosphate": true,
		"e442": true, "ammonium phosphatide": true, "e450": true, "diphosphate": true, "e451": true, "triphosphate": true, "e452": true,
		"polyphosphate": true, "e540": true, "dicalcium diphosphate": true, "e541": true,
		" aluminium phosphate": true, "e543": true, "calcium sodium polyphosphate": true,
		"e544": true, "calcium polyphosphate": true, "e1410": true, "phosphate starch": true,
		"e1412": true, "distarch phosphate": true, "e1413": true, "phosphated distarch phosphate": true,
		"e1414": true, "acetylated distarch phosphate": true, "e1442": true, "hydroxypropyl distarch phosphate": true,
		"cane sugar": true, "maltodextrin": true, "artificial flavor": true, "datem": true,
		"diacetyl tartaric esters of monoglycerides": true, "diacetyl tartaric acid esters": true,
		"diacetyl tartaric acid esters of diglycerides": true, "corn malt extract": true, "malt extract": true, "malt syrup": true,
		"e471": true, "e250": true, "sodium tripolyphosphate": true, "e316": true, "sodium erythorbate": true, "e155": true, "brown ht": true,
		" caramellsed milk powder": true, "natural flavouring": true, "colour": true, "modified palm oil": true, "emulsifiers: lecithin": true,
		"sweetened condensed whole milk ": true, "sweetened condensed milk": true, "disodium guanylate": true, "interesterified soybean oil": true,
		"e627": true, "refined sunflower oil": true, "vegetable oils ": true, "vegetables oil": true, "natural flavor": true, "liquid sugar": true,
		"flavourings": true,
	}
)
